package cn.com.clubank.weihang.manage.member.dao;

import cn.com.clubank.weihang.manage.member.pojo.CarBrand;
import java.util.List;

/**
 * 车辆品牌表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface CarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String carBrandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int insert(CarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    CarBrand selectByPrimaryKey(String carBrandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    List<CarBrand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarBrand record);
}