package cn.com.clubank.weihang.manage.member.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cn.com.clubank.weihang.manage.member.pojo.CouponList;

/**
 * 券兑换信息表（数据访问层接口）
 * 
 * @author Liangwl
 *
 */
public interface CouponListMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coupon_list
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String couponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coupon_list
	 *
	 * @mbggenerated
	 */
	int insert(CouponList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coupon_list
	 *
	 * @mbggenerated
	 */
	CouponList selectByPrimaryKey(String couponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coupon_list
	 *
	 * @mbggenerated
	 */
	List<CouponList> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coupon_list
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CouponList record);

	/**
	 * 
	 * @param CustomerId
	 * @return
	 */
	List<CouponList> selectByCustomerId(String customerId);

	/**
	 * 查询客户优惠券列表(区分状态)
	 * 
	 * @param customerId
	 * @param couponStatus
	 * @return
	 */
	List<Map<String, String>> selectByCustomerIdAndStatus(@Param("customerId") String customerId,
			@Param("couponStatus") Integer couponStatus);

	/**
	 * 批量插入
	 * 
	 * @param list
	 */
	void insertBatch(List<CouponList> list);

	/**
	 * 更新优惠券是否过期状态
	 */
	void updateCouponStatus();

	/**
	 * 获取可用优惠券数量
	 * 
	 * @param customerId
	 * @return
	 */
	int selectCountByCustomerId(String customerId);

	/**
	 * 查询兑换记录数
	 * 
	 * @param couponName
	 * @param customerName
	 * @param couponStatus
	 * @return
	 */
	int selectCountCouponExchangeRecord(@Param("couponName") String couponName,
			@Param("customerName") String customerName, @Param("couponStatus") Integer couponStatus);

	/**
	 * 查询兑换记录
	 * 
	 * @param start
	 * @param pageSize
	 * @param couponName
	 * @param customerName
	 * @param couponStatus
	 * @return
	 */
	List<Map<String, String>> selectCouponExchangeRecordList(@Param("start") Integer start,
			@Param("pageSize") Integer pageSize, @Param("couponName") String couponName,
			@Param("customerName") String customerName, @Param("couponStatus") Integer couponStatus);

	/**
	 * 后台：根据优惠券兑换记录主键查询兑换详情
	 * 
	 * @param couponId
	 * @return
	 */
	Map<String, String> selectCouponExchangeDetailByPrimaryKey(String couponId);

	/**
	 * 获取折扣券Discount coupon
	 * 
	 * @param customerId
	 * @param list
	 * @return
	 */
	List<Map<String, String>> selectAvailableDiscountCouponList(@Param("customerId") String customerId,
			@Param("list") List<String> list);

	/**
	 * 获取抵扣券Deduction coupon
	 * 
	 * @param customerId
	 * @return
	 */
	List<Map<String, String>> selectAvailableDeductionCouponList(String customerId);

	/**
	 * 获取兑换券Exchange coupon
	 * 
	 * @param customerId
	 * @param list
	 * @return
	 */
	List<Map<String, String>> selectAvailableExchangeCouponList(@Param("customerId") String customerId,
			@Param("list") List<String> list);

	/**
	 * 获取服务券Service coupon
	 * 
	 * @param customerId
	 * @param serviceCouponType
	 * @return
	 */
	List<Map<String, String>> selectAvailableServiceCouponList(@Param("customerId") String customerId,
			@Param("list") List<String> list);

	/**
	 * 根据券码查询优惠券
	 * 
	 * @param couponCode
	 * @return
	 */
	CouponList selectByCouponCode(@Param("couponCode") String couponCode);

	/**
	 * 查询优惠券信息
	 * 
	 * @param couponCode
	 * @return
	 */
	Map<String, String> selectCouponInfoByCouponCode(@Param("couponCode") String couponCode);

	/**
	 * 根据商品id查询未失效的优惠券列表
	 * 
	 * @param productId
	 * @return
	 */
	List<CouponList> selectByProductId(String productId);

	/**
	 * 根据商品skuId查询未失效的优惠券列表
	 * 
	 * @param skuId
	 * @return
	 */
	List<CouponList> selectBySkuId(String skuId);
}