package cn.com.clubank.weihang.manage.user.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cn.com.clubank.weihang.manage.user.pojo.BaseUser;

/**
 * 用户信息表（数据访问层接口）
 * 
 * @author Liangwl
 *
 */
public interface BaseUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table base_user
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table base_user
	 * 
	 * @mbggenerated
	 */
	int insert(BaseUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table base_user
	 * 
	 * @mbggenerated
	 */
	BaseUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table base_user
	 * 
	 * @mbggenerated
	 */
	List<BaseUser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table base_user
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BaseUser record);

	int updateSelectiveByPrimaryKey(BaseUser baseUser);

	/**
	 * 通过职位查询用户名(真实姓名)和头像
	 * 
	 * @param duty
	 * @return
	 */
	List<BaseUser> selectByDuty(Integer duty);

	/**
	 * 根据用户id获取姓名
	 * 
	 * @param userId
	 * @return
	 */
	String selectNameById(String userId);

	/**
	 * 根据账户查询员工信息
	 * 
	 * @param account
	 * @return
	 */
	BaseUser selectByAccount(String account);

	/**
	 * 根据账户查询员工信息
	 * 
	 * @param account
	 * @return
	 */
	BaseUser selectByMobile(String mobile);

	/**
	 * 后台：根据条件查询用户数量
	 * 
	 * @param account
	 * @param realname
	 * @param departmentId
	 * @param userStatus
	 * @return
	 */
	int selectBaseUserCount(@Param("account") String account, @Param("realname") String realname,
			@Param("departmentId") String departmentId, @Param("userStatus") Integer userStatus);

	/**
	 * 根据帐号（模糊）、姓名（模糊）、部门主键、状态分页查询列表
	 * 
	 * @param account
	 * @param realname
	 * @param departmentId
	 * @param userStatus
	 * @param start
	 * @param pageSize
	 * @return
	 */
	List<Map<String, String>> selectBaseUserList(@Param("account") String account, @Param("realname") String realname,
			@Param("departmentId") String departmentId, @Param("userStatus") Integer userStatus,
			@Param("start") int start, @Param("pageSize") int pageSize);

	/**
	 * 后台：根据用户主键查询用户信息
	 * 
	 * @param userId
	 * @return
	 */
	Map<String, String> selectUserInfoByPrimaryKey(String userId);

	/**
	 * 后台：根据用户主键查询用户角色信息
	 * 
	 * @param userId
	 * @return
	 */
	List<Map<String, String>> selectUserRoleByUserId(String userId);
}