package cn.com.clubank.weihang.manage.product.dao;

import cn.com.clubank.weihang.manage.product.pojo.ShopIntegral;
import java.util.List;

/**
 * 积分商城商品表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface ShopIntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_integral
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String siId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_integral
     *
     * @mbggenerated
     */
    int insert(ShopIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_integral
     *
     * @mbggenerated
     */
    ShopIntegral selectByPrimaryKey(String siId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_integral
     *
     * @mbggenerated
     */
    List<ShopIntegral> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_integral
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopIntegral record);
}