package cn.com.clubank.weihang.manage.dataItem.dao;

import cn.com.clubank.weihang.manage.dataItem.pojo.BaseDataitemDetail;
import java.util.List;

/**
 * 数据字典明细表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface BaseDataitemDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dataitem_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String bdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dataitem_detail
     *
     * @mbggenerated
     */
    int insert(BaseDataitemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dataitem_detail
     *
     * @mbggenerated
     */
    BaseDataitemDetail selectByPrimaryKey(String bdId);
    
    /**
     * 通过分类ID查询名称和值
     * @param dataId
     * @return 数据字典明细表名称和值对象集合
     */
    List<BaseDataitemDetail> selectBySortKey(String dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dataitem_detail
     *
     * @mbggenerated
     */
    List<BaseDataitemDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dataitem_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseDataitemDetail record);
    
    /**
     * 获得数据字典分类下明细列表
     * @param dataId
     * @return
     */
    List<BaseDataitemDetail> selectDetailByDataId(String dataId);
}