package cn.com.clubank.weihang.manage.dataItem.dao;

import cn.com.clubank.weihang.manage.dataItem.pojo.BaseDataitem;
import java.util.List;

/**
 * 数据字典分类表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface BaseDataitemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base_dataitem
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String dataId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base_dataitem
	 * @mbggenerated
	 */
	int insert(BaseDataitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base_dataitem
	 * @mbggenerated
	 */
	BaseDataitem selectByPrimaryKey(String dataId);
	
	/**
	 * 通过参数key(code)查询数据
	 * @param code
	 * @return 数据字典分类表对象
	 */
	BaseDataitem selectByCode(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base_dataitem
	 * @mbggenerated
	 */
	List<BaseDataitem> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table base_dataitem
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BaseDataitem record);
}