package cn.com.clubank.weihang.manage.material.dao;

import cn.com.clubank.weihang.manage.material.pojo.WorkMaterialStorage;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

/**
 * 物料仓储表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface WorkMaterialStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String wiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    int insert(WorkMaterialStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    WorkMaterialStorage selectByPrimaryKey(String wiId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    WorkMaterialStorage selectByCode(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    List<WorkMaterialStorage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_storage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkMaterialStorage record);
    
    /**
     * 获取维修材料名称列表
     */
    List<WorkMaterialStorage> selectItemName();
    
    /**
     * 通过输入的材料名，模糊查询获得材料列表
     * @param temName
     * @return
     */
    List<WorkMaterialStorage> selectByItemName(String itemName);
    
	/**
	 * 分页查询：通过物料名模糊查询，进行分页
	 * @param itemName    物料名
	 * @param startIndex  起始页
	 * @param pageSize    每页行数
	 * @return
	 */
    List<Map<String,Object>> findPage(@Param("itemName") String itemName, @Param("startIndex") Integer startIndex, @Param("pageSize") Integer pageSize);
    
    /**
     * 按物料名模糊查询到的总条数
     * @param itemName  属性值
     * @return
     */
    int findPageTotal(@Param("itemName") String itemName);
    
    /**
     * 通过分类ID获得物料列表
     * @param categoryId 分类ID
     * @return
     */
    List<WorkMaterialStorage> selectMaterialListByCategoryId(String categoryId);
}