package cn.com.clubank.weihang.manage.material.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.com.clubank.weihang.manage.material.pojo.WorkMaterialCategory;

/**
 * 物料分类表（数据访问层接口）
 * @author Liangwl
 *
 */
public interface WorkMaterialCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String wicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_category
     *
     * @mbggenerated
     */
    int insert(WorkMaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_category
     *
     * @mbggenerated
     */
    WorkMaterialCategory selectByPrimaryKey(String wicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_category
     *
     * @mbggenerated
     */
    List<WorkMaterialCategory> selectAll();
    
    /**
     * 获得所有父分类
     * @return
     */
    List<WorkMaterialCategory> selectAllParent();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_material_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkMaterialCategory record);
    
    /**
	 * 分页查询：通过分类名模糊查询，进行分页
	 * @param categoryName 物料分类名
	 * @param startIndex   起始索引
	 * @param pageSize     每页行数
	 * @return
	 */
    List<WorkMaterialCategory> findPage(@Param("categoryName") String cname, @Param("startIndex") Integer startIndex, @Param("pageSize") Integer pageSize);
    
    /**
     * 按物料分类名模糊查询到的总条数
     * @param categoryName 物料分类名
     * @return
     */
    int findPageTotal(@Param("categoryName") String categoryName);
    
    /**
     * 查询分类ID与分类名称
     * @return
     */
    List<WorkMaterialCategory> selectWicId();
    
    /**
     * 查询所有根分类
     * @return
     */
    List<WorkMaterialCategory> selectRootCategory();
    
    /**
     * 根据wicId获取节点对象
     * @param wicId
     * @return
     */
    WorkMaterialCategory selectNode(String wicId);
    
    /**
     * 查询wicId下的所有子节点
     * @param parentId
     * @return
     */
    List<WorkMaterialCategory> selectChildNode(String parentId);
}